name: Create and publish image
permissions:
  contents: read         # Needed to check out the repository
  packages: write        # Needed to push images to GitHub Container Registry (ghcr.io)

on:
  push:
    branches: [ master ]
    tags:
    - "v*.*.*"

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write  # For generating attestations
      id-token: write      # For OIDC token authentication
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Extract metadata for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ github.repository_owner }}/instance-manager,ghcr.io/${{ github.repository_owner }}/instance-manager
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,format=short
          labels: |
            org.opencontainers.image.source=https://github.com/keikoproj/instance-manager
            org.opencontainers.image.description=A Kubernetes operator that manages the lifecycle of EC2 instances within a Kubernetes cluster
            org.opencontainers.image.title=Instance Manager
            org.opencontainers.image.documentation=https://github.com/keikoproj/instance-manager/blob/master/README.md
            org.opencontainers.image.url=https://github.com/keikoproj/instance-manager
            org.opencontainers.image.vendor=keikoproj
            org.opencontainers.image.authors=Keikoproj Contributors
            org.opencontainers.image.licenses=Apache-2.0
          annotations: |
            org.opencontainers.image.description=A Kubernetes controller for creating and managing worker node instance groups across multiple providers
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.source=https://github.com/keikoproj/instance-manager
            org.opencontainers.image.url=https://github.com/keikoproj/instance-manager/blob/master/README.md
            org.opencontainers.image.vendor=keikoproj
            org.opencontainers.image.authors=Keikoproj Contributors
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp || format('{0:yyyy-MM-ddTHH:mm:ssZ}', github.event.repository.updated_at) }}
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=Instance Manager
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push cross-platform image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CREATED=${{ github.event.head_commit.timestamp || format('{0:yyyy-MM-ddTHH:mm:ssZ}', github.event.repository.updated_at) }}
            VERSION=${{ github.ref_name }}
            REVISION=${{ github.sha }}

      - name: Generate artifact attestation (dockerhub)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: docker.io/${{ github.repository_owner }}/instance-manager
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation (ghcr)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/instance-manager
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
